-- DRA Platform Schema (Supabase / Postgres)
-- Generated by Database Architect Agent

-- 1. Clients Table
CREATE TABLE IF NOT EXISTS public.clients (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    logo_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for slug lookups (common usage)
CREATE INDEX IF NOT EXISTS idx_clients_slug ON public.clients(slug);

-- 2. Connectors Table
-- Stores encrypted credentials for GA4, Shopify, WooCommerce
CREATE TABLE IF NOT EXISTS public.connectors (
    id SERIAL PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL, -- 'ga4', 'woocommerce', 'shopify'
    config_json TEXT NOT NULL, -- Encrypted JSON string
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fetching client connectors
CREATE INDEX IF NOT EXISTS idx_connectors_client_id ON public.connectors(client_id);

-- 3. Jobs Table
-- Records reconciliation runs and high-level status
CREATE TABLE IF NOT EXISTS public.jobs (
    id SERIAL PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'running', 'completed', 'failed'
    result_summary JSONB, -- Stores high-level stats like match_rate, discrepancy
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    logs TEXT -- Simple text logs for MVP
);

-- Index for job history queries
CREATE INDEX IF NOT EXISTS idx_jobs_client_id ON public.jobs(client_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON public.jobs(status);

-- 4. Results Table (Detailed)
-- Stores the full detailed report if needed (or we keep it in jobs.result_summary for MVP)
-- For MVP, we'll skip a heavy line-item result table and stick to JSONB in Jobs for flexibility.

-- ROW LEVEL SECURITY (RLS) POLICIES
-- NOTE: In a real Supabase setup, we would enable RLS and create policies based on auth.uid()
-- matching a 'users' table or 'organization_members' table.
-- For MVP Schema, we define the tables but comment out RLS to keep local dev simple unless requested.

-- ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.connectors ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- =============================================================================
-- SCHEMA MIGRATIONS - Add missing columns safely (idempotent)
-- =============================================================================

-- Update jobs table to add logs column if not exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='jobs' AND column_name='logs') THEN
        ALTER TABLE public.jobs ADD COLUMN logs TEXT;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='jobs' AND column_name='completed_at') THEN
        ALTER TABLE public.jobs ADD COLUMN completed_at TIMESTAMPTZ;
    END IF;
END $$;

-- Update connectors table to add is_active if not exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='connectors' AND column_name='is_active') THEN
        ALTER TABLE public.connectors ADD COLUMN is_active BOOLEAN DEFAULT TRUE;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='connectors' AND column_name='updated_at') THEN
        ALTER TABLE public.connectors ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
    END IF;
END $$;
